BEGIN;
--
-- Create model Tenant
--
CREATE TABLE "core_tenant" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL);
--
-- Create model User
--
CREATE TABLE "core_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "role" varchar(20) NOT NULL, "tenant_id" bigint NOT NULL);
CREATE TABLE "core_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "core_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Project
--
CREATE TABLE "core_project" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "status" varchar(20) NOT NULL, "description" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "owner_id" bigint NOT NULL, "tenant_id" bigint NOT NULL);
--
-- Create model Budget
--
CREATE TABLE "core_budget" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "total_value" numeric(14, 2) NOT NULL, "notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "project_id" bigint NOT NULL UNIQUE, "tenant_id" bigint NOT NULL);
--
-- Create model Document
--
CREATE TABLE "core_document" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "doc_type" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "file" varchar(100) NULL, "notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "project_id" bigint NOT NULL, "tenant_id" bigint NOT NULL);
--
-- Create model Expense
--
CREATE TABLE "core_expense" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "amount" numeric(14, 2) NOT NULL, "paid_at" date NOT NULL, "description" varchar(255) NOT NULL, "project_id" bigint NOT NULL, "tenant_id" bigint NOT NULL);
--
-- Create model Parcel
--
CREATE TABLE "core_parcel" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "boundary" geometry(MULTIPOLYGON,4326) NOT NULL, "area_sq_m" numeric(14, 2) NULL, "perimeter_m" numeric(14, 2) NULL, "created_at" timestamp with time zone NOT NULL, "project_id" bigint NOT NULL, "tenant_id" bigint NOT NULL);
--
-- Create model Payment
--
CREATE TABLE "core_payment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "amount" numeric(14, 2) NOT NULL, "received_at" date NOT NULL, "description" varchar(255) NOT NULL, "project_id" bigint NOT NULL, "tenant_id" bigint NOT NULL);
CREATE INDEX "core_tenant_slug_4150dd86_like" ON "core_tenant" ("slug" varchar_pattern_ops);
ALTER TABLE "core_user" ADD CONSTRAINT "core_user_tenant_id_8a6e30cc_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_username_36e4f7f7_like" ON "core_user" ("username" varchar_pattern_ops);
CREATE INDEX "core_user_tenant_id_8a6e30cc" ON "core_user" ("tenant_id");
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_user_id_group_id_c82fcad1_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_user_id_70b4d9b8_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_group_id_fe8c697f_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_groups_user_id_70b4d9b8" ON "core_user_groups" ("user_id");
CREATE INDEX "core_user_groups_group_id_fe8c697f" ON "core_user_groups" ("group_id");
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permissions_user_id_permission_id_73ea0daa_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permissions_user_id_085123d3_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permi_permission_id_35ccf601_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_user_permissions_user_id_085123d3" ON "core_user_user_permissions" ("user_id");
CREATE INDEX "core_user_user_permissions_permission_id_35ccf601" ON "core_user_user_permissions" ("permission_id");
ALTER TABLE "core_project" ADD CONSTRAINT "core_project_owner_id_26945739_fk_core_user_id" FOREIGN KEY ("owner_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_project" ADD CONSTRAINT "core_project_tenant_id_560cac1a_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_project_owner_id_26945739" ON "core_project" ("owner_id");
CREATE INDEX "core_project_tenant_id_560cac1a" ON "core_project" ("tenant_id");
ALTER TABLE "core_budget" ADD CONSTRAINT "core_budget_project_id_0de65dd3_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_budget" ADD CONSTRAINT "core_budget_tenant_id_2a58f195_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_budget_tenant_id_2a58f195" ON "core_budget" ("tenant_id");
ALTER TABLE "core_document" ADD CONSTRAINT "core_document_project_id_6a7bc98f_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_document" ADD CONSTRAINT "core_document_tenant_id_e75f828e_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_document_project_id_6a7bc98f" ON "core_document" ("project_id");
CREATE INDEX "core_document_tenant_id_e75f828e" ON "core_document" ("tenant_id");
ALTER TABLE "core_expense" ADD CONSTRAINT "core_expense_project_id_065daf74_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_expense" ADD CONSTRAINT "core_expense_tenant_id_db5ef368_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_expense_project_id_065daf74" ON "core_expense" ("project_id");
CREATE INDEX "core_expense_tenant_id_db5ef368" ON "core_expense" ("tenant_id");
ALTER TABLE "core_parcel" ADD CONSTRAINT "core_parcel_project_id_e8654741_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_parcel" ADD CONSTRAINT "core_parcel_tenant_id_3046a20d_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_parcel_boundary_f985ed7f_id" ON "core_parcel" USING GIST ("boundary");
CREATE INDEX "core_parcel_project_id_e8654741" ON "core_parcel" ("project_id");
CREATE INDEX "core_parcel_tenant_id_3046a20d" ON "core_parcel" ("tenant_id");
ALTER TABLE "core_payment" ADD CONSTRAINT "core_payment_project_id_1e745004_fk_core_project_id" FOREIGN KEY ("project_id") REFERENCES "core_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_payment" ADD CONSTRAINT "core_payment_tenant_id_97fbb04f_fk_core_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "core_tenant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_payment_project_id_1e745004" ON "core_payment" ("project_id");
CREATE INDEX "core_payment_tenant_id_97fbb04f" ON "core_payment" ("tenant_id");
COMMIT;
